/*
 * Bob API
 * Access your employees data with the Bob API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.CustomTableMetadata;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CustomTableMetadataList
 */
public class CustomTableMetadataListTest {
    private final CustomTableMetadataList model = new CustomTableMetadataList();

    /**
     * Model tests for CustomTableMetadataList
     */
    @Test
    public void testCustomTableMetadataList() {
        // TODO: test CustomTableMetadataList
    }

    /**
     * Test the property 'tables'
     */
    @Test
    public void tablesTest() {
        // TODO: test tables
    }

}
