/*
 * Bob API
 * Access your employees data with the Bob API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.File;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for DocumentsUploadConfidentialFileRequest
 */
public class DocumentsUploadConfidentialFileRequestTest {
    private final DocumentsUploadConfidentialFileRequest model = new DocumentsUploadConfidentialFileRequest();

    /**
     * Model tests for DocumentsUploadConfidentialFileRequest
     */
    @Test
    public void testDocumentsUploadConfidentialFileRequest() {
        // TODO: test DocumentsUploadConfidentialFileRequest
    }

    /**
     * Test the property '_file'
     */
    @Test
    public void _fileTest() {
        // TODO: test _file
    }

}
