/*
 * Bob API
 * Access your employees data with the Bob API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.AboutPart;
import com.konfigthis.client.model.PersonalPart;
import com.konfigthis.client.model.WorkPart;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for EmployeeProfile
 */
public class EmployeeProfileTest {
    private final EmployeeProfile model = new EmployeeProfile();

    /**
     * Model tests for EmployeeProfile
     */
    @Test
    public void testEmployeeProfile() {
        // TODO: test EmployeeProfile
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'firstName'
     */
    @Test
    public void firstNameTest() {
        // TODO: test firstName
    }

    /**
     * Test the property 'surname'
     */
    @Test
    public void surnameTest() {
        // TODO: test surname
    }

    /**
     * Test the property 'email'
     */
    @Test
    public void emailTest() {
        // TODO: test email
    }

    /**
     * Test the property 'displayName'
     */
    @Test
    public void displayNameTest() {
        // TODO: test displayName
    }

    /**
     * Test the property 'personal'
     */
    @Test
    public void personalTest() {
        // TODO: test personal
    }

    /**
     * Test the property 'about'
     */
    @Test
    public void aboutTest() {
        // TODO: test about
    }

    /**
     * Test the property 'work'
     */
    @Test
    public void workTest() {
        // TODO: test work
    }

}
