/*
 * Bob API
 * Access your employees data with the Bob API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for EmployeeDocumentWithDownloadLink
 */
public class EmployeeDocumentWithDownloadLinkTest {
    private final EmployeeDocumentWithDownloadLink model = new EmployeeDocumentWithDownloadLink();

    /**
     * Model tests for EmployeeDocumentWithDownloadLink
     */
    @Test
    public void testEmployeeDocumentWithDownloadLink() {
        // TODO: test EmployeeDocumentWithDownloadLink
    }

    /**
     * Test the property 'documentName'
     */
    @Test
    public void documentNameTest() {
        // TODO: test documentName
    }

    /**
     * Test the property 'downloadLink'
     */
    @Test
    public void downloadLinkTest() {
        // TODO: test downloadLink
    }

}
