/*
 * Bob API
 * Access your employees data with the Bob API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.EmployeeTerminationNoticePeriod;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.LocalDate;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for EmployeeTermination
 */
public class EmployeeTerminationTest {
    private final EmployeeTermination model = new EmployeeTermination();

    /**
     * Model tests for EmployeeTermination
     */
    @Test
    public void testEmployeeTermination() {
        // TODO: test EmployeeTermination
    }

    /**
     * Test the property 'terminationDate'
     */
    @Test
    public void terminationDateTest() {
        // TODO: test terminationDate
    }

    /**
     * Test the property 'terminationReason'
     */
    @Test
    public void terminationReasonTest() {
        // TODO: test terminationReason
    }

    /**
     * Test the property 'reasonType'
     */
    @Test
    public void reasonTypeTest() {
        // TODO: test reasonType
    }

    /**
     * Test the property 'noticePeriod'
     */
    @Test
    public void noticePeriodTest() {
        // TODO: test noticePeriod
    }

    /**
     * Test the property 'lastDayOfWork'
     */
    @Test
    public void lastDayOfWorkTest() {
        // TODO: test lastDayOfWork
    }

}
