/*
 * Bob API
 * Access your employees data with the Bob API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ImportAttendanceEvent
 */
public class ImportAttendanceEventTest {
    private final ImportAttendanceEvent model = new ImportAttendanceEvent();

    /**
     * Model tests for ImportAttendanceEvent
     */
    @Test
    public void testImportAttendanceEvent() {
        // TODO: test ImportAttendanceEvent
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'clockIn'
     */
    @Test
    public void clockInTest() {
        // TODO: test clockIn
    }

    /**
     * Test the property 'clockOut'
     */
    @Test
    public void clockOutTest() {
        // TODO: test clockOut
    }

}
