/*
 * Bob API
 * Access your employees data with the Bob API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.FieldTypeData;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ObjectsMetadataFieldType
 */
public class ObjectsMetadataFieldTypeTest {
    private final ObjectsMetadataFieldType model = new ObjectsMetadataFieldType();

    /**
     * Model tests for ObjectsMetadataFieldType
     */
    @Test
    public void testObjectsMetadataFieldType() {
        // TODO: test ObjectsMetadataFieldType
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'typeData'
     */
    @Test
    public void typeDataTest() {
        // TODO: test typeData
    }

}
