/*
 * Bob API
 * Access your employees data with the Bob API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PeopleUpdateEmployeeRecordRequestPersonal
 */
public class PeopleUpdateEmployeeRecordRequestPersonalTest {
    private final PeopleUpdateEmployeeRecordRequestPersonal model = new PeopleUpdateEmployeeRecordRequestPersonal();

    /**
     * Model tests for PeopleUpdateEmployeeRecordRequestPersonal
     */
    @Test
    public void testPeopleUpdateEmployeeRecordRequestPersonal() {
        // TODO: test PeopleUpdateEmployeeRecordRequestPersonal
    }

    /**
     * Test the property 'birthDate'
     */
    @Test
    public void birthDateTest() {
        // TODO: test birthDate
    }

}
