/*
 * Bob API
 * Access your employees data with the Bob API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PersonalPart
 */
public class PersonalPartTest {
    private final PersonalPart model = new PersonalPart();

    /**
     * Model tests for PersonalPart
     */
    @Test
    public void testPersonalPart() {
        // TODO: test PersonalPart
    }

    /**
     * Test the property 'honorific'
     */
    @Test
    public void honorificTest() {
        // TODO: test honorific
    }

    /**
     * Test the property 'shortBirthDate'
     */
    @Test
    public void shortBirthDateTest() {
        // TODO: test shortBirthDate
    }

    /**
     * Test the property 'gender'
     */
    @Test
    public void genderTest() {
        // TODO: test gender
    }

}
