/*
 * Bob API
 * Access your employees data with the Bob API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.YearsOfServiceIncrements;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for Policy
 */
public class PolicyTest {
    private final Policy model = new Policy();

    /**
     * Model tests for Policy
     */
    @Test
    public void testPolicy() {
        // TODO: test Policy
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'allowance'
     */
    @Test
    public void allowanceTest() {
        // TODO: test allowance
    }

    /**
     * Test the property 'maxBalance'
     */
    @Test
    public void maxBalanceTest() {
        // TODO: test maxBalance
    }

    /**
     * Test the property 'minBalance'
     */
    @Test
    public void minBalanceTest() {
        // TODO: test minBalance
    }

    /**
     * Test the property 'yosIncrease'
     */
    @Test
    public void yosIncreaseTest() {
        // TODO: test yosIncrease
    }

    /**
     * Test the property 'minTimeOffRequestDuration'
     */
    @Test
    public void minTimeOffRequestDurationTest() {
        // TODO: test minTimeOffRequestDuration
    }

    /**
     * Test the property 'approvalRequired'
     */
    @Test
    public void approvalRequiredTest() {
        // TODO: test approvalRequired
    }

    /**
     * Test the property 'unit'
     */
    @Test
    public void unitTest() {
        // TODO: test unit
    }

}
