/*
 * Bob API
 * Access your employees data with the Bob API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PositionEntriesInner
 */
public class PositionEntriesInnerTest {
    private final PositionEntriesInner model = new PositionEntriesInner();

    /**
     * Model tests for PositionEntriesInner
     */
    @Test
    public void testPositionEntriesInner() {
        // TODO: test PositionEntriesInner
    }

    /**
     * Test the property 'positionFte'
     */
    @Test
    public void positionFteTest() {
        // TODO: test positionFte
    }

    /**
     * Test the property 'positionEffectiveDate'
     */
    @Test
    public void positionEffectiveDateTest() {
        // TODO: test positionEffectiveDate
    }

    /**
     * Test the property 'positionEmploymentType'
     */
    @Test
    public void positionEmploymentTypeTest() {
        // TODO: test positionEmploymentType
    }

    /**
     * Test the property 'positionStatus'
     */
    @Test
    public void positionStatusTest() {
        // TODO: test positionStatus
    }

    /**
     * Test the property 'positionActualStartDate'
     */
    @Test
    public void positionActualStartDateTest() {
        // TODO: test positionActualStartDate
    }

    /**
     * Test the property 'positionReason'
     */
    @Test
    public void positionReasonTest() {
        // TODO: test positionReason
    }

    /**
     * Test the property 'positionPositionType'
     */
    @Test
    public void positionPositionTypeTest() {
        // TODO: test positionPositionType
    }

    /**
     * Test the property 'positionFilledBy'
     */
    @Test
    public void positionFilledByTest() {
        // TODO: test positionFilledBy
    }

    /**
     * Test the property 'positionJob'
     */
    @Test
    public void positionJobTest() {
        // TODO: test positionJob
    }

    /**
     * Test the property 'positionRecruitmentStatus'
     */
    @Test
    public void positionRecruitmentStatusTest() {
        // TODO: test positionRecruitmentStatus
    }

    /**
     * Test the property 'positionName'
     */
    @Test
    public void positionNameTest() {
        // TODO: test positionName
    }

    /**
     * Test the property 'positionDepartment'
     */
    @Test
    public void positionDepartmentTest() {
        // TODO: test positionDepartment
    }

    /**
     * Test the property 'positionSite'
     */
    @Test
    public void positionSiteTest() {
        // TODO: test positionSite
    }

    /**
     * Test the property 'positionExpectedStartDate'
     */
    @Test
    public void positionExpectedStartDateTest() {
        // TODO: test positionExpectedStartDate
    }

    /**
     * Test the property 'positionManagerPositionId'
     */
    @Test
    public void positionManagerPositionIdTest() {
        // TODO: test positionManagerPositionId
    }

    /**
     * Test the property 'positionManagerPositionFilledBy'
     */
    @Test
    public void positionManagerPositionFilledByTest() {
        // TODO: test positionManagerPositionFilledBy
    }

}
