/*
 * Bob API
 * Access your employees data with the Bob API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.EmployeeFilter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ReadEmployeesRequestReference
 */
public class ReadEmployeesRequestReferenceTest {
    private final ReadEmployeesRequestReference model = new ReadEmployeesRequestReference();

    /**
     * Model tests for ReadEmployeesRequestReference
     */
    @Test
    public void testReadEmployeesRequestReference() {
        // TODO: test ReadEmployeesRequestReference
    }

    /**
     * Test the property 'fields'
     */
    @Test
    public void fieldsTest() {
        // TODO: test fields
    }

    /**
     * Test the property 'filters'
     */
    @Test
    public void filtersTest() {
        // TODO: test filters
    }

    /**
     * Test the property 'showInactive'
     */
    @Test
    public void showInactiveTest() {
        // TODO: test showInactive
    }

    /**
     * Test the property 'humanReadable'
     */
    @Test
    public void humanReadableTest() {
        // TODO: test humanReadable
    }

}
