/*
 * Bob API
 * Access your employees data with the Bob API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.SubmitTimeoffRequestDiffHoursDurationsInner;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for SubmitTimeoffRequestDiffHours
 */
public class SubmitTimeoffRequestDiffHoursTest {
    private final SubmitTimeoffRequestDiffHours model = new SubmitTimeoffRequestDiffHours();

    /**
     * Model tests for SubmitTimeoffRequestDiffHours
     */
    @Test
    public void testSubmitTimeoffRequestDiffHours() {
        // TODO: test SubmitTimeoffRequestDiffHours
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'policyType'
     */
    @Test
    public void policyTypeTest() {
        // TODO: test policyType
    }

    /**
     * Test the property 'startDate'
     */
    @Test
    public void startDateTest() {
        // TODO: test startDate
    }

    /**
     * Test the property 'endDate'
     */
    @Test
    public void endDateTest() {
        // TODO: test endDate
    }

    /**
     * Test the property 'durations'
     */
    @Test
    public void durationsTest() {
        // TODO: test durations
    }

    /**
     * Test the property 'skipManagerApproval'
     */
    @Test
    public void skipManagerApprovalTest() {
        // TODO: test skipManagerApproval
    }

    /**
     * Test the property 'approver'
     */
    @Test
    public void approverTest() {
        // TODO: test approver
    }

    /**
     * Test the property 'reasonCode'
     */
    @Test
    public void reasonCodeTest() {
        // TODO: test reasonCode
    }

}
