/*
 * Bob API
 * Access your employees data with the Bob API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.LocalDate;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for SubmitTimeoffRequestDiffHoursDurationsInner
 */
public class SubmitTimeoffRequestDiffHoursDurationsInnerTest {
    private final SubmitTimeoffRequestDiffHoursDurationsInner model = new SubmitTimeoffRequestDiffHoursDurationsInner();

    /**
     * Model tests for SubmitTimeoffRequestDiffHoursDurationsInner
     */
    @Test
    public void testSubmitTimeoffRequestDiffHoursDurationsInner() {
        // TODO: test SubmitTimeoffRequestDiffHoursDurationsInner
    }

    /**
     * Test the property 'date'
     */
    @Test
    public void dateTest() {
        // TODO: test date
    }

    /**
     * Test the property 'hours'
     */
    @Test
    public void hoursTest() {
        // TODO: test hours
    }

    /**
     * Test the property 'minutes'
     */
    @Test
    public void minutesTest() {
        // TODO: test minutes
    }

}
