/*
 * Bob API
 * Access your employees data with the Bob API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.EmployeeTerminationNoticePeriod;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.LocalDate;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * EmployeeTermination
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class EmployeeTermination {
  public static final String SERIALIZED_NAME_TERMINATION_DATE = "terminationDate";
  @SerializedName(SERIALIZED_NAME_TERMINATION_DATE)
  private LocalDate terminationDate;

  public static final String SERIALIZED_NAME_TERMINATION_REASON = "terminationReason";
  @SerializedName(SERIALIZED_NAME_TERMINATION_REASON)
  private String terminationReason;

  public static final String SERIALIZED_NAME_REASON_TYPE = "reasonType";
  @SerializedName(SERIALIZED_NAME_REASON_TYPE)
  private String reasonType;

  public static final String SERIALIZED_NAME_NOTICE_PERIOD = "noticePeriod";
  @SerializedName(SERIALIZED_NAME_NOTICE_PERIOD)
  private EmployeeTerminationNoticePeriod noticePeriod;

  public static final String SERIALIZED_NAME_LAST_DAY_OF_WORK = "lastDayOfWork";
  @SerializedName(SERIALIZED_NAME_LAST_DAY_OF_WORK)
  private LocalDate lastDayOfWork;

  public EmployeeTermination() {
  }

  public EmployeeTermination terminationDate(LocalDate terminationDate) {
    
    
    
    
    this.terminationDate = terminationDate;
    return this;
  }

   /**
   * The employee&#39;s termination date
   * @return terminationDate
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "Mon Sep 22 17:00:00 PDT 2025", required = true, value = "The employee's termination date")

  public LocalDate getTerminationDate() {
    return terminationDate;
  }


  public void setTerminationDate(LocalDate terminationDate) {
    
    
    
    this.terminationDate = terminationDate;
  }


  public EmployeeTermination terminationReason(String terminationReason) {
    
    
    
    
    this.terminationReason = terminationReason;
    return this;
  }

   /**
   * The ID of the &#39;terminationReason&#39; list entry
   * @return terminationReason
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Redundant", value = "The ID of the 'terminationReason' list entry")

  public String getTerminationReason() {
    return terminationReason;
  }


  public void setTerminationReason(String terminationReason) {
    
    
    
    this.terminationReason = terminationReason;
  }


  public EmployeeTermination reasonType(String reasonType) {
    
    
    
    
    this.reasonType = reasonType;
    return this;
  }

   /**
   * The ID of the &#39;lifecycleReasonType&#39; list entry
   * @return reasonType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "End of Contract", value = "The ID of the 'lifecycleReasonType' list entry")

  public String getReasonType() {
    return reasonType;
  }


  public void setReasonType(String reasonType) {
    
    
    
    this.reasonType = reasonType;
  }


  public EmployeeTermination noticePeriod(EmployeeTerminationNoticePeriod noticePeriod) {
    
    
    
    
    this.noticePeriod = noticePeriod;
    return this;
  }

   /**
   * Get noticePeriod
   * @return noticePeriod
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public EmployeeTerminationNoticePeriod getNoticePeriod() {
    return noticePeriod;
  }


  public void setNoticePeriod(EmployeeTerminationNoticePeriod noticePeriod) {
    
    
    
    this.noticePeriod = noticePeriod;
  }


  public EmployeeTermination lastDayOfWork(LocalDate lastDayOfWork) {
    
    
    
    
    this.lastDayOfWork = lastDayOfWork;
    return this;
  }

   /**
   * Get lastDayOfWork
   * @return lastDayOfWork
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Sun Sep 21 17:00:00 PDT 2025", value = "")

  public LocalDate getLastDayOfWork() {
    return lastDayOfWork;
  }


  public void setLastDayOfWork(LocalDate lastDayOfWork) {
    
    
    
    this.lastDayOfWork = lastDayOfWork;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the EmployeeTermination instance itself
   */
  public EmployeeTermination putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EmployeeTermination employeeTermination = (EmployeeTermination) o;
    return Objects.equals(this.terminationDate, employeeTermination.terminationDate) &&
        Objects.equals(this.terminationReason, employeeTermination.terminationReason) &&
        Objects.equals(this.reasonType, employeeTermination.reasonType) &&
        Objects.equals(this.noticePeriod, employeeTermination.noticePeriod) &&
        Objects.equals(this.lastDayOfWork, employeeTermination.lastDayOfWork)&&
        Objects.equals(this.additionalProperties, employeeTermination.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(terminationDate, terminationReason, reasonType, noticePeriod, lastDayOfWork, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EmployeeTermination {\n");
    sb.append("    terminationDate: ").append(toIndentedString(terminationDate)).append("\n");
    sb.append("    terminationReason: ").append(toIndentedString(terminationReason)).append("\n");
    sb.append("    reasonType: ").append(toIndentedString(reasonType)).append("\n");
    sb.append("    noticePeriod: ").append(toIndentedString(noticePeriod)).append("\n");
    sb.append("    lastDayOfWork: ").append(toIndentedString(lastDayOfWork)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("terminationDate");
    openapiFields.add("terminationReason");
    openapiFields.add("reasonType");
    openapiFields.add("noticePeriod");
    openapiFields.add("lastDayOfWork");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("terminationDate");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to EmployeeTermination
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!EmployeeTermination.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in EmployeeTermination is not found in the empty JSON string", EmployeeTermination.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : EmployeeTermination.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      if ((jsonObj.get("terminationReason") != null && !jsonObj.get("terminationReason").isJsonNull()) && !jsonObj.get("terminationReason").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `terminationReason` to be a primitive type in the JSON string but got `%s`", jsonObj.get("terminationReason").toString()));
      }
      if ((jsonObj.get("reasonType") != null && !jsonObj.get("reasonType").isJsonNull()) && !jsonObj.get("reasonType").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `reasonType` to be a primitive type in the JSON string but got `%s`", jsonObj.get("reasonType").toString()));
      }
      // validate the optional field `noticePeriod`
      if (jsonObj.get("noticePeriod") != null && !jsonObj.get("noticePeriod").isJsonNull()) {
        EmployeeTerminationNoticePeriod.validateJsonObject(jsonObj.getAsJsonObject("noticePeriod"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!EmployeeTermination.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'EmployeeTermination' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<EmployeeTermination> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(EmployeeTermination.class));

       return (TypeAdapter<T>) new TypeAdapter<EmployeeTermination>() {
           @Override
           public void write(JsonWriter out, EmployeeTermination value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public EmployeeTermination read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             EmployeeTermination instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of EmployeeTermination given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of EmployeeTermination
  * @throws IOException if the JSON string is invalid with respect to EmployeeTermination
  */
  public static EmployeeTermination fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, EmployeeTermination.class);
  }

 /**
  * Convert an instance of EmployeeTermination to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

