/*
 * Bob API
 * Access your employees data with the Bob API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * An event indicating clock-in, clock-out or both
 */
@ApiModel(description = "An event indicating clock-in, clock-out or both")@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class ImportAttendanceEvent {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_CLOCK_IN = "clockIn";
  @SerializedName(SERIALIZED_NAME_CLOCK_IN)
  private String clockIn;

  public static final String SERIALIZED_NAME_CLOCK_OUT = "clockOut";
  @SerializedName(SERIALIZED_NAME_CLOCK_OUT)
  private String clockOut;

  public ImportAttendanceEvent() {
  }

  public ImportAttendanceEvent id(String id) {
    
    
    
    
    this.id = id;
    return this;
  }

   /**
   * The id value to identify the customer by. Will fetch the employee based on the field (type) selected in &lt;i&gt;idType&lt;/i&gt;.
   * @return id
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "12356733644", required = true, value = "The id value to identify the customer by. Will fetch the employee based on the field (type) selected in <i>idType</i>.")

  public String getId() {
    return id;
  }


  public void setId(String id) {
    
    
    
    this.id = id;
  }


  public ImportAttendanceEvent clockIn(String clockIn) {
    
    
    
    
    this.clockIn = clockIn;
    return this;
  }

   /**
   * The timestamp to log as a clock-in date-time in local time
   * @return clockIn
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "2022-06-12T08:00", value = "The timestamp to log as a clock-in date-time in local time")

  public String getClockIn() {
    return clockIn;
  }


  public void setClockIn(String clockIn) {
    
    
    
    this.clockIn = clockIn;
  }


  public ImportAttendanceEvent clockOut(String clockOut) {
    
    
    
    
    this.clockOut = clockOut;
    return this;
  }

   /**
   * The timestamp to log as a clock-out date-time in local time.
   * @return clockOut
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "2022-06-12T17:00", value = "The timestamp to log as a clock-out date-time in local time.")

  public String getClockOut() {
    return clockOut;
  }


  public void setClockOut(String clockOut) {
    
    
    
    this.clockOut = clockOut;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the ImportAttendanceEvent instance itself
   */
  public ImportAttendanceEvent putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ImportAttendanceEvent importAttendanceEvent = (ImportAttendanceEvent) o;
    return Objects.equals(this.id, importAttendanceEvent.id) &&
        Objects.equals(this.clockIn, importAttendanceEvent.clockIn) &&
        Objects.equals(this.clockOut, importAttendanceEvent.clockOut)&&
        Objects.equals(this.additionalProperties, importAttendanceEvent.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, clockIn, clockOut, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ImportAttendanceEvent {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    clockIn: ").append(toIndentedString(clockIn)).append("\n");
    sb.append("    clockOut: ").append(toIndentedString(clockOut)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("id");
    openapiFields.add("clockIn");
    openapiFields.add("clockOut");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("id");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to ImportAttendanceEvent
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!ImportAttendanceEvent.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ImportAttendanceEvent is not found in the empty JSON string", ImportAttendanceEvent.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : ImportAttendanceEvent.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      if (!jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      if ((jsonObj.get("clockIn") != null && !jsonObj.get("clockIn").isJsonNull()) && !jsonObj.get("clockIn").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `clockIn` to be a primitive type in the JSON string but got `%s`", jsonObj.get("clockIn").toString()));
      }
      if ((jsonObj.get("clockOut") != null && !jsonObj.get("clockOut").isJsonNull()) && !jsonObj.get("clockOut").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `clockOut` to be a primitive type in the JSON string but got `%s`", jsonObj.get("clockOut").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ImportAttendanceEvent.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ImportAttendanceEvent' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ImportAttendanceEvent> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ImportAttendanceEvent.class));

       return (TypeAdapter<T>) new TypeAdapter<ImportAttendanceEvent>() {
           @Override
           public void write(JsonWriter out, ImportAttendanceEvent value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public ImportAttendanceEvent read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             ImportAttendanceEvent instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ImportAttendanceEvent given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ImportAttendanceEvent
  * @throws IOException if the JSON string is invalid with respect to ImportAttendanceEvent
  */
  public static ImportAttendanceEvent fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ImportAttendanceEvent.class);
  }

 /**
  * Convert an instance of ImportAttendanceEvent to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

