/*
 * Bob API
 * Access your employees data with the Bob API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.LocalDate;
import java.util.UUID;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * TimeoffChange
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class TimeoffChange {
  /**
   * Change type - created, canceled or deleted.
   */
  @JsonAdapter(ChangeTypeEnum.Adapter.class)
 public enum ChangeTypeEnum {
    CREATED("Created"),
    
    CANCELED("Canceled"),
    
    DELETED("Deleted");

    private String value;

    ChangeTypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static ChangeTypeEnum fromValue(String value) {
      for (ChangeTypeEnum b : ChangeTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<ChangeTypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final ChangeTypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public ChangeTypeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return ChangeTypeEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_CHANGE_TYPE = "changeType";
  @SerializedName(SERIALIZED_NAME_CHANGE_TYPE)
  private ChangeTypeEnum changeType;

  public static final String SERIALIZED_NAME_EMPLOYEE_ID = "employeeId";
  @SerializedName(SERIALIZED_NAME_EMPLOYEE_ID)
  private UUID employeeId;

  public static final String SERIALIZED_NAME_EMPLOYEE_DISPLAY_NAME = "employeeDisplayName";
  @SerializedName(SERIALIZED_NAME_EMPLOYEE_DISPLAY_NAME)
  private String employeeDisplayName;

  public static final String SERIALIZED_NAME_EMPLOYEE_EMAIL = "employeeEmail";
  @SerializedName(SERIALIZED_NAME_EMPLOYEE_EMAIL)
  private String employeeEmail;

  public static final String SERIALIZED_NAME_REQUEST_ID = "requestId";
  @SerializedName(SERIALIZED_NAME_REQUEST_ID)
  private Integer requestId;

  public static final String SERIALIZED_NAME_POLICY_TYPE_DISPLAY_NAME = "policyTypeDisplayName";
  @SerializedName(SERIALIZED_NAME_POLICY_TYPE_DISPLAY_NAME)
  private String policyTypeDisplayName;

  /**
   * The type of request duration.&lt;br&gt; &lt;b&gt;portionOnRange&lt;/b&gt; is when the request is for every morning or every afternoon during the days requested.&lt;br&gt; &lt;b&gt;hoursOnRange&lt;/b&gt; is when the request is for X hours every day during the days requested.
   */
  @JsonAdapter(TypeEnum.Adapter.class)
 public enum TypeEnum {
    DAYS("days"),
    
    HOURS("hours"),
    
    PORTIONONRANGE("portionOnRange"),
    
    HOURSONRANGE("hoursOnRange");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<TypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final TypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public TypeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return TypeEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  private TypeEnum type;

  public static final String SERIALIZED_NAME_START_DATE = "startDate";
  @SerializedName(SERIALIZED_NAME_START_DATE)
  private LocalDate startDate;

  public static final String SERIALIZED_NAME_START_PORTION = "startPortion";
  @SerializedName(SERIALIZED_NAME_START_PORTION)
  private String startPortion;

  public static final String SERIALIZED_NAME_END_DATE = "endDate";
  @SerializedName(SERIALIZED_NAME_END_DATE)
  private LocalDate endDate;

  public static final String SERIALIZED_NAME_END_PORTION = "endPortion";
  @SerializedName(SERIALIZED_NAME_END_PORTION)
  private String endPortion;

  public static final String SERIALIZED_NAME_DAY_PORTION = "dayPortion";
  @SerializedName(SERIALIZED_NAME_DAY_PORTION)
  private String dayPortion;

  public static final String SERIALIZED_NAME_DATE = "date";
  @SerializedName(SERIALIZED_NAME_DATE)
  private LocalDate date;

  public static final String SERIALIZED_NAME_HOURS_ON_DATE = "hoursOnDate";
  @SerializedName(SERIALIZED_NAME_HOURS_ON_DATE)
  private Integer hoursOnDate;

  public static final String SERIALIZED_NAME_DAILY_HOURS = "dailyHours";
  @SerializedName(SERIALIZED_NAME_DAILY_HOURS)
  private Double dailyHours;

  /**
   * The unit used for the totalDuration and totalCost - either &#39;days&#39; or &#39;hours&#39;
   */
  @JsonAdapter(DurationUnitEnum.Adapter.class)
 public enum DurationUnitEnum {
    DAYS("days"),
    
    HOURS("hours");

    private String value;

    DurationUnitEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static DurationUnitEnum fromValue(String value) {
      for (DurationUnitEnum b : DurationUnitEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<DurationUnitEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final DurationUnitEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public DurationUnitEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return DurationUnitEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_DURATION_UNIT = "durationUnit";
  @SerializedName(SERIALIZED_NAME_DURATION_UNIT)
  private DurationUnitEnum durationUnit;

  public static final String SERIALIZED_NAME_TOTAL_DURATION = "totalDuration";
  @SerializedName(SERIALIZED_NAME_TOTAL_DURATION)
  private Double totalDuration;

  public static final String SERIALIZED_NAME_TOTAL_COST = "totalCost";
  @SerializedName(SERIALIZED_NAME_TOTAL_COST)
  private Double totalCost;

  public static final String SERIALIZED_NAME_CHANGE_REASON = "changeReason";
  @SerializedName(SERIALIZED_NAME_CHANGE_REASON)
  private String changeReason;

  public TimeoffChange() {
  }

  public TimeoffChange changeType(ChangeTypeEnum changeType) {
    
    
    
    
    this.changeType = changeType;
    return this;
  }

   /**
   * Change type - created, canceled or deleted.
   * @return changeType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Change type - created, canceled or deleted.")

  public ChangeTypeEnum getChangeType() {
    return changeType;
  }


  public void setChangeType(ChangeTypeEnum changeType) {
    
    
    
    this.changeType = changeType;
  }


  public TimeoffChange employeeId(UUID employeeId) {
    
    
    
    
    this.employeeId = employeeId;
    return this;
  }

   /**
   * Employee ID
   * @return employeeId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Employee ID")

  public UUID getEmployeeId() {
    return employeeId;
  }


  public void setEmployeeId(UUID employeeId) {
    
    
    
    this.employeeId = employeeId;
  }


  public TimeoffChange employeeDisplayName(String employeeDisplayName) {
    
    
    
    
    this.employeeDisplayName = employeeDisplayName;
    return this;
  }

   /**
   * Employee display name.
   * @return employeeDisplayName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Employee display name.")

  public String getEmployeeDisplayName() {
    return employeeDisplayName;
  }


  public void setEmployeeDisplayName(String employeeDisplayName) {
    
    
    
    this.employeeDisplayName = employeeDisplayName;
  }


  public TimeoffChange employeeEmail(String employeeEmail) {
    
    
    
    
    this.employeeEmail = employeeEmail;
    return this;
  }

   /**
   * Employee email address.
   * @return employeeEmail
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Employee email address.")

  public String getEmployeeEmail() {
    return employeeEmail;
  }


  public void setEmployeeEmail(String employeeEmail) {
    
    
    
    this.employeeEmail = employeeEmail;
  }


  public TimeoffChange requestId(Integer requestId) {
    
    
    
    
    this.requestId = requestId;
    return this;
  }

   /**
   * TimeOff Request ID.
   * @return requestId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "TimeOff Request ID.")

  public Integer getRequestId() {
    return requestId;
  }


  public void setRequestId(Integer requestId) {
    
    
    
    this.requestId = requestId;
  }


  public TimeoffChange policyTypeDisplayName(String policyTypeDisplayName) {
    
    
    
    
    this.policyTypeDisplayName = policyTypeDisplayName;
    return this;
  }

   /**
   * Display name of the policy type.
   * @return policyTypeDisplayName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Display name of the policy type.")

  public String getPolicyTypeDisplayName() {
    return policyTypeDisplayName;
  }


  public void setPolicyTypeDisplayName(String policyTypeDisplayName) {
    
    
    
    this.policyTypeDisplayName = policyTypeDisplayName;
  }


  public TimeoffChange type(TypeEnum type) {
    
    
    
    
    this.type = type;
    return this;
  }

   /**
   * The type of request duration.&lt;br&gt; &lt;b&gt;portionOnRange&lt;/b&gt; is when the request is for every morning or every afternoon during the days requested.&lt;br&gt; &lt;b&gt;hoursOnRange&lt;/b&gt; is when the request is for X hours every day during the days requested.
   * @return type
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The type of request duration.<br> <b>portionOnRange</b> is when the request is for every morning or every afternoon during the days requested.<br> <b>hoursOnRange</b> is when the request is for X hours every day during the days requested.")

  public TypeEnum getType() {
    return type;
  }


  public void setType(TypeEnum type) {
    
    
    
    this.type = type;
  }


  public TimeoffChange startDate(LocalDate startDate) {
    
    
    
    
    this.startDate = startDate;
    return this;
  }

   /**
   * Date of the first day of the time off (not relevant for requests using the hours type).
   * @return startDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Date of the first day of the time off (not relevant for requests using the hours type).")

  public LocalDate getStartDate() {
    return startDate;
  }


  public void setStartDate(LocalDate startDate) {
    
    
    
    this.startDate = startDate;
  }


  public TimeoffChange startPortion(String startPortion) {
    
    
    
    
    this.startPortion = startPortion;
    return this;
  }

   /**
   * What portion of the first day is included - all_day, morning or afternoon (relevant for requests using the Days type).
   * @return startPortion
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "What portion of the first day is included - all_day, morning or afternoon (relevant for requests using the Days type).")

  public String getStartPortion() {
    return startPortion;
  }


  public void setStartPortion(String startPortion) {
    
    
    
    this.startPortion = startPortion;
  }


  public TimeoffChange endDate(LocalDate endDate) {
    
    
    
    
    this.endDate = endDate;
    return this;
  }

   /**
   * Date of the last day of the time off (not relevant for requests using the hours type).
   * @return endDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Date of the last day of the time off (not relevant for requests using the hours type).")

  public LocalDate getEndDate() {
    return endDate;
  }


  public void setEndDate(LocalDate endDate) {
    
    
    
    this.endDate = endDate;
  }


  public TimeoffChange endPortion(String endPortion) {
    
    
    
    
    this.endPortion = endPortion;
    return this;
  }

   /**
   * What portion of the last day is included - all_day, morning or afternoon (relevant for requests using the Days type).
   * @return endPortion
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "What portion of the last day is included - all_day, morning or afternoon (relevant for requests using the Days type).")

  public String getEndPortion() {
    return endPortion;
  }


  public void setEndPortion(String endPortion) {
    
    
    
    this.endPortion = endPortion;
  }


  public TimeoffChange dayPortion(String dayPortion) {
    
    
    
    
    this.dayPortion = dayPortion;
    return this;
  }

   /**
   * What portion of the request&#39;s days is included - morning or afternoon (relevant for requests using the portionOnRange type).
   * @return dayPortion
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "What portion of the request's days is included - morning or afternoon (relevant for requests using the portionOnRange type).")

  public String getDayPortion() {
    return dayPortion;
  }


  public void setDayPortion(String dayPortion) {
    
    
    
    this.dayPortion = dayPortion;
  }


  public TimeoffChange date(LocalDate date) {
    
    
    
    
    this.date = date;
    return this;
  }

   /**
   * Date of the time off (relevant for requests using the Hours type)
   * @return date
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Date of the time off (relevant for requests using the Hours type)")

  public LocalDate getDate() {
    return date;
  }


  public void setDate(LocalDate date) {
    
    
    
    this.date = date;
  }


  public TimeoffChange hoursOnDate(Integer hoursOnDate) {
    
    
    
    
    this.hoursOnDate = hoursOnDate;
    return this;
  }

   /**
   * The time off duration in hours for the date (relevant for requests using the Hours type).
   * @return hoursOnDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The time off duration in hours for the date (relevant for requests using the Hours type).")

  public Integer getHoursOnDate() {
    return hoursOnDate;
  }


  public void setHoursOnDate(Integer hoursOnDate) {
    
    
    
    this.hoursOnDate = hoursOnDate;
  }


  public TimeoffChange dailyHours(Double dailyHours) {
    
    
    
    
    this.dailyHours = dailyHours;
    return this;
  }

  public TimeoffChange dailyHours(Integer dailyHours) {
    
    
    
    
    this.dailyHours = dailyHours.doubleValue();
    return this;
  }

   /**
   * The time off duration in hours for every day in the request (relevant for requests using the hoursOnRange type)
   * @return dailyHours
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The time off duration in hours for every day in the request (relevant for requests using the hoursOnRange type)")

  public Double getDailyHours() {
    return dailyHours;
  }


  public void setDailyHours(Double dailyHours) {
    
    
    
    this.dailyHours = dailyHours;
  }


  public TimeoffChange durationUnit(DurationUnitEnum durationUnit) {
    
    
    
    
    this.durationUnit = durationUnit;
    return this;
  }

   /**
   * The unit used for the totalDuration and totalCost - either &#39;days&#39; or &#39;hours&#39;
   * @return durationUnit
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The unit used for the totalDuration and totalCost - either 'days' or 'hours'")

  public DurationUnitEnum getDurationUnit() {
    return durationUnit;
  }


  public void setDurationUnit(DurationUnitEnum durationUnit) {
    
    
    
    this.durationUnit = durationUnit;
  }


  public TimeoffChange totalDuration(Double totalDuration) {
    
    
    
    
    this.totalDuration = totalDuration;
    return this;
  }

  public TimeoffChange totalDuration(Integer totalDuration) {
    
    
    
    
    this.totalDuration = totalDuration.doubleValue();
    return this;
  }

   /**
   * The total amount of time the request covers, including regular days off such as weekends
   * @return totalDuration
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The total amount of time the request covers, including regular days off such as weekends")

  public Double getTotalDuration() {
    return totalDuration;
  }


  public void setTotalDuration(Double totalDuration) {
    
    
    
    this.totalDuration = totalDuration;
  }


  public TimeoffChange totalCost(Double totalCost) {
    
    
    
    
    this.totalCost = totalCost;
    return this;
  }

  public TimeoffChange totalCost(Integer totalCost) {
    
    
    
    
    this.totalCost = totalCost.doubleValue();
    return this;
  }

   /**
   * The amount that will be deducted from the balance
   * @return totalCost
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The amount that will be deducted from the balance")

  public Double getTotalCost() {
    return totalCost;
  }


  public void setTotalCost(Double totalCost) {
    
    
    
    this.totalCost = totalCost;
  }


  public TimeoffChange changeReason(String changeReason) {
    
    
    
    
    this.changeReason = changeReason;
    return this;
  }

   /**
   * Request change reason
   * @return changeReason
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Request change reason")

  public String getChangeReason() {
    return changeReason;
  }


  public void setChangeReason(String changeReason) {
    
    
    
    this.changeReason = changeReason;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the TimeoffChange instance itself
   */
  public TimeoffChange putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TimeoffChange timeoffChange = (TimeoffChange) o;
    return Objects.equals(this.changeType, timeoffChange.changeType) &&
        Objects.equals(this.employeeId, timeoffChange.employeeId) &&
        Objects.equals(this.employeeDisplayName, timeoffChange.employeeDisplayName) &&
        Objects.equals(this.employeeEmail, timeoffChange.employeeEmail) &&
        Objects.equals(this.requestId, timeoffChange.requestId) &&
        Objects.equals(this.policyTypeDisplayName, timeoffChange.policyTypeDisplayName) &&
        Objects.equals(this.type, timeoffChange.type) &&
        Objects.equals(this.startDate, timeoffChange.startDate) &&
        Objects.equals(this.startPortion, timeoffChange.startPortion) &&
        Objects.equals(this.endDate, timeoffChange.endDate) &&
        Objects.equals(this.endPortion, timeoffChange.endPortion) &&
        Objects.equals(this.dayPortion, timeoffChange.dayPortion) &&
        Objects.equals(this.date, timeoffChange.date) &&
        Objects.equals(this.hoursOnDate, timeoffChange.hoursOnDate) &&
        Objects.equals(this.dailyHours, timeoffChange.dailyHours) &&
        Objects.equals(this.durationUnit, timeoffChange.durationUnit) &&
        Objects.equals(this.totalDuration, timeoffChange.totalDuration) &&
        Objects.equals(this.totalCost, timeoffChange.totalCost) &&
        Objects.equals(this.changeReason, timeoffChange.changeReason)&&
        Objects.equals(this.additionalProperties, timeoffChange.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(changeType, employeeId, employeeDisplayName, employeeEmail, requestId, policyTypeDisplayName, type, startDate, startPortion, endDate, endPortion, dayPortion, date, hoursOnDate, dailyHours, durationUnit, totalDuration, totalCost, changeReason, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TimeoffChange {\n");
    sb.append("    changeType: ").append(toIndentedString(changeType)).append("\n");
    sb.append("    employeeId: ").append(toIndentedString(employeeId)).append("\n");
    sb.append("    employeeDisplayName: ").append(toIndentedString(employeeDisplayName)).append("\n");
    sb.append("    employeeEmail: ").append(toIndentedString(employeeEmail)).append("\n");
    sb.append("    requestId: ").append(toIndentedString(requestId)).append("\n");
    sb.append("    policyTypeDisplayName: ").append(toIndentedString(policyTypeDisplayName)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    startDate: ").append(toIndentedString(startDate)).append("\n");
    sb.append("    startPortion: ").append(toIndentedString(startPortion)).append("\n");
    sb.append("    endDate: ").append(toIndentedString(endDate)).append("\n");
    sb.append("    endPortion: ").append(toIndentedString(endPortion)).append("\n");
    sb.append("    dayPortion: ").append(toIndentedString(dayPortion)).append("\n");
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("    hoursOnDate: ").append(toIndentedString(hoursOnDate)).append("\n");
    sb.append("    dailyHours: ").append(toIndentedString(dailyHours)).append("\n");
    sb.append("    durationUnit: ").append(toIndentedString(durationUnit)).append("\n");
    sb.append("    totalDuration: ").append(toIndentedString(totalDuration)).append("\n");
    sb.append("    totalCost: ").append(toIndentedString(totalCost)).append("\n");
    sb.append("    changeReason: ").append(toIndentedString(changeReason)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("changeType");
    openapiFields.add("employeeId");
    openapiFields.add("employeeDisplayName");
    openapiFields.add("employeeEmail");
    openapiFields.add("requestId");
    openapiFields.add("policyTypeDisplayName");
    openapiFields.add("type");
    openapiFields.add("startDate");
    openapiFields.add("startPortion");
    openapiFields.add("endDate");
    openapiFields.add("endPortion");
    openapiFields.add("dayPortion");
    openapiFields.add("date");
    openapiFields.add("hoursOnDate");
    openapiFields.add("dailyHours");
    openapiFields.add("durationUnit");
    openapiFields.add("totalDuration");
    openapiFields.add("totalCost");
    openapiFields.add("changeReason");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to TimeoffChange
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!TimeoffChange.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in TimeoffChange is not found in the empty JSON string", TimeoffChange.openapiRequiredFields.toString()));
        }
      }
      if ((jsonObj.get("changeType") != null && !jsonObj.get("changeType").isJsonNull()) && !jsonObj.get("changeType").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `changeType` to be a primitive type in the JSON string but got `%s`", jsonObj.get("changeType").toString()));
      }
      if ((jsonObj.get("employeeId") != null && !jsonObj.get("employeeId").isJsonNull()) && !jsonObj.get("employeeId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `employeeId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("employeeId").toString()));
      }
      if ((jsonObj.get("employeeDisplayName") != null && !jsonObj.get("employeeDisplayName").isJsonNull()) && !jsonObj.get("employeeDisplayName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `employeeDisplayName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("employeeDisplayName").toString()));
      }
      if ((jsonObj.get("employeeEmail") != null && !jsonObj.get("employeeEmail").isJsonNull()) && !jsonObj.get("employeeEmail").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `employeeEmail` to be a primitive type in the JSON string but got `%s`", jsonObj.get("employeeEmail").toString()));
      }
      if ((jsonObj.get("policyTypeDisplayName") != null && !jsonObj.get("policyTypeDisplayName").isJsonNull()) && !jsonObj.get("policyTypeDisplayName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `policyTypeDisplayName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("policyTypeDisplayName").toString()));
      }
      if ((jsonObj.get("type") != null && !jsonObj.get("type").isJsonNull()) && !jsonObj.get("type").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `type` to be a primitive type in the JSON string but got `%s`", jsonObj.get("type").toString()));
      }
      if ((jsonObj.get("startPortion") != null && !jsonObj.get("startPortion").isJsonNull()) && !jsonObj.get("startPortion").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `startPortion` to be a primitive type in the JSON string but got `%s`", jsonObj.get("startPortion").toString()));
      }
      if ((jsonObj.get("endPortion") != null && !jsonObj.get("endPortion").isJsonNull()) && !jsonObj.get("endPortion").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `endPortion` to be a primitive type in the JSON string but got `%s`", jsonObj.get("endPortion").toString()));
      }
      if ((jsonObj.get("dayPortion") != null && !jsonObj.get("dayPortion").isJsonNull()) && !jsonObj.get("dayPortion").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `dayPortion` to be a primitive type in the JSON string but got `%s`", jsonObj.get("dayPortion").toString()));
      }
      if ((jsonObj.get("durationUnit") != null && !jsonObj.get("durationUnit").isJsonNull()) && !jsonObj.get("durationUnit").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `durationUnit` to be a primitive type in the JSON string but got `%s`", jsonObj.get("durationUnit").toString()));
      }
      if ((jsonObj.get("changeReason") != null && !jsonObj.get("changeReason").isJsonNull()) && !jsonObj.get("changeReason").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `changeReason` to be a primitive type in the JSON string but got `%s`", jsonObj.get("changeReason").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!TimeoffChange.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'TimeoffChange' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<TimeoffChange> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(TimeoffChange.class));

       return (TypeAdapter<T>) new TypeAdapter<TimeoffChange>() {
           @Override
           public void write(JsonWriter out, TimeoffChange value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public TimeoffChange read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             TimeoffChange instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of TimeoffChange given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of TimeoffChange
  * @throws IOException if the JSON string is invalid with respect to TimeoffChange
  */
  public static TimeoffChange fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, TimeoffChange.class);
  }

 /**
  * Convert an instance of TimeoffChange to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

