/*
 * Bob API
 * Access your employees data with the Bob API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.Error;
import com.konfigthis.client.model.FilterInstruction;
import com.konfigthis.client.model.GetPositionsRequest;
import com.konfigthis.client.model.PositionEntriesInner;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ObjectsApi
 */
@Disabled
public class ObjectsApiTest {

    private static ObjectsApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new ObjectsApi(apiClient);
    }

    /**
     * Read company positions
     *
     * Returns a list of the company positions, filtered by the specified attributes.  &lt;br /&gt;&lt;br&gt;&lt;b&gt;Note&lt;/b&gt;
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void searchCompanyPositionsTest() throws ApiException {
        List<String> fields = null;
        List<FilterInstruction> filters = null;
        Boolean includeHumanReadable = null;
        List<PositionEntriesInner> response = api.searchCompanyPositions(fields, filters)
                .includeHumanReadable(includeHumanReadable)
                .execute();
        // TODO: test validations
    }

}
