/*
 * Bob API
 * Access your employees data with the Bob API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.Error;
import com.konfigthis.client.model.OnboardingWizards;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for OnboardingApi
 */
@Disabled
public class OnboardingApiTest {

    private static OnboardingApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new OnboardingApi(apiClient);
    }

    /**
     * Get a summary of all onboarding wizards.
     *
     * Wizard info includes Wizard ID, name and description.&lt;br /&gt;&lt;b&gt;Supported user types:&lt;/b&gt; Service.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getWizardSummaryTest() throws ApiException {
        OnboardingWizards response = api.getWizardSummary()
                .execute();
        // TODO: test validations
    }

}
